
export default function PrivacyPolicyPage() {
    return (
      <div className="container py-12 md:py-16 max-w-4xl mx-auto">
        <h1 className="text-3xl md:text-4xl font-bold text-primary mb-6">Privacy Policy</h1>
        <div className="prose dark:prose-invert max-w-none text-foreground/80">
          <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
          
          <p>
            “This Privacy Policy (“Policy”) is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. The Policy is an ‘electronic record’ as contemplated under section 2(t) of the Information Technology Act, 2000 and the rules. This Policy being an electronic record is generated by a computer system and does not require any physical or digital signature.”
          </p>
  
          <h2>INTRODUCTION</h2>
          <p>
            The online store www.honestyprinthouse.in (“Online Store”) is owned and operated by Honesty Enterprise, under the laws of India having its registered office at Shop No.9, Plot No.387,Matoshree CHS, Sector-19C, Koparkhairane, Navi Mumbai – 4400709.
          </p>
          <p>
            Users are requested to read and understand the Policy very carefully before using or accessing the Online Store. Through this Policy, Honesty Enterprise intends to convey the manner in which the user’s information is collated and used by Honesty Enterprise Shopping while providing the services of the Online Store. This Policy is binding on every user of the Online Store and users who do not agree with the terms of this Policy should not use or access the Online Store.
          </p>
          <p>
            Honesty Enterprise reserves its right to change, edit, alter, amend, modify, review, revise or substitute this Policy with or without notice. By using the Online Store, the user’s signify they have carefully read, understood and agree to be bound by this Policy and the users expressly and voluntarily accept this Policy including any change, modification or substitution made to the Policy from time to time. Honesty Enterprise reserves its right to refuse services to any user who does not accept or violates the terms of this Policy.
          </p>
  
          <h2>User Information</h2>
          <p>
            User Information typically refers to the personal data or details that are collected from individuals when they interact with a service, website, or online platform. It includes a range of data such as:
          </p>
          <ul>
            <li><strong>Personal Identification Details:</strong> Name, address, email, phone number, date of birth, etc.</li>
            <li><strong>Account Details:</strong> Username, password, purchase history, preferences, etc.</li>
            <li><strong>Payment Information:</strong> Credit card details, billing address, payment preferences.</li>
            <li><strong>Usage Data:</strong> Browsing behavior, device information, IP address, cookies, and location data.</li>
            <li><strong>Communication Data:</strong> Customer service interactions, feedback, reviews, and support requests.</li>
          </ul>
          <p>
            The collection, use, and protection of this information are typically outlined in a Privacy Policy to ensure users understand how their data will be handled.
          </p>
  
          <h2>Use of Information & Disclosure</h2>
          <p>
            Use of Information & Disclosure typically refers to how an organization or service provider uses the personal information they collect from users and under what circumstances they may share or disclose this information. Here’s what it typically includes:
          </p>
          <h3>Use of Information:</h3>
          <ul>
            <li><strong>Service Improvement:</strong> To personalize and enhance user experience, improve services, and develop new features.</li>
            <li><strong>Transactional Purposes:</strong> To process orders, payments, and shipments, and to communicate regarding transactions.</li>
            <li><strong>Marketing and Promotions:</strong> To send promotional materials, offers, or newsletters (usually with user consent).</li>
            <li><strong>Legal Compliance:</strong> To comply with laws and regulations, prevent fraud, or resolve disputes.</li>
          </ul>
          <h3>Disclosure of Information:</h3>
          <ul>
            <li><strong>Third-Party Service Providers:</strong> Information may be shared with trusted third parties for payment processing, delivery, or other necessary services.</li>
            <li><strong>Legal Requirements:</strong> Information may be disclosed if required by law, court orders, or governmental authorities.</li>
            <li><strong>Business Transfers:</strong> In case of mergers, acquisitions, or bankruptcy, user data may be transferred to new owners.</li>
            <li><strong>Public Forums:</strong> Any information shared publicly by users in forums, reviews, or social media may be disclosed and visible to others.</li>
          </ul>
          <p>
            The goal of the Use of Information & Disclosure section in a privacy policy is to ensure transparency about how user data will be used and shared.
          </p>

          <h2>Security & User Restriction</h2>
          <p>
            Security & User Restriction refers to the measures taken to protect user information and the limitations placed on how users can interact with the platform or service. Here’s what it typically involves:
          </p>
          <h3>Security Measures:</h3>
          <ul>
            <li><strong>Data Encryption:</strong> Protecting sensitive user information like payment details and personal data through encryption technology.</li>
            <li><strong>Secure Transactions:</strong> Ensuring that all transactions conducted on the platform are secure and protected from unauthorized access.</li>
            <li><strong>Access Control:</strong> Limiting access to sensitive data only to authorized personnel or systems to prevent misuse.</li>
            <li><strong>Regular Audits and Monitoring:</strong> Continuous monitoring of the system to identify and prevent security threats and vulnerabilities.</li>
          </ul>
          <h3>User Restrictions:</h3>
          <ul>
            <li><strong>Prohibited Activities:</strong> Users are restricted from engaging in illegal activities such as hacking, phishing, spamming, or posting harmful content.</li>
            <li><strong>Account Misuse:</strong> Users should not share their account credentials with others, and they must keep their passwords confidential.</li>
            <li><strong>Violation of Terms:</strong> Users who violate the platform’s terms, such as misusing services or posting unauthorized content, may be restricted or banned from using the service.</li>
            <li><strong>Access to Certain Features:</strong> Some features of the platform may only be accessible to users who meet specific criteria or have appropriate permissions.</li>
          </ul>
          <p>
            The Security & User Restriction section in a privacy policy or terms of service ensures both the protection of user data and the appropriate usage of the platform by its users.
          </p>

          <h2>Third Party Websites and Links</h2>
          <p>
            Third Party Websites and Links refers to the inclusion of links on a website or platform that lead to external websites or services not owned or operated by the site in question. Here’s what this typically includes:
          </p>
          <h3>External Links:</h3>
          <ul>
            <li><strong>Links to Third-Party Websites:</strong> The platform may contain links to external websites that are not under its control. These third-party sites may have different privacy practices and policies.</li>
            <li><strong>Responsibility:</strong> The platform is not responsible for the content, privacy practices, or security measures of any third-party websites linked from the platform. Users are encouraged to review the privacy policies of any external sites they visit.</li>
            <li><strong>Affiliate Links:</strong> Some links may be affiliate links, meaning the platform may earn a commission or referral fee if users make purchases through those links.</li>
          </ul>
          <h3>Disclaimer:</h3>
          <ul>
            <li><strong>No Control Over Third-Party Sites:</strong> The platform disclaims any responsibility for the accuracy, content, or availability of third-party websites or services. The inclusion of links does not imply endorsement or approval of the external website.</li>
            <li><strong>Use at Your Own Risk:</strong> Users click on third-party links at their own risk, and the platform is not liable for any issues that arise from interacting with these external sites.</li>
          </ul>
          <p>
            The Third Party Websites and Links section in a privacy policy is important for informing users about the potential risks of navigating to external sites and clarifying the platform’s limited responsibility regarding those sites.
          </p>
  
          <h2>Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please <a href="/contact-us">contact us</a>.
          </p>
        </div>
      </div>
    );
  }
  